# Generated by Django 4.2 on 2023-04-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('address_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Manzil nomi')),
                ('address_cn', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес китайский')),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Имя категория')),
                ('title_uz', models.CharField(max_length=150, verbose_name='Kategoriya nomi')),
                ('title_cn', models.CharField(max_length=150, verbose_name='Имя китайский')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new'), ('processing', 'processing'), ('finished', 'finished'), ('cancel', 'cancel')], default='new', max_length=255)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jami')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('rate', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Telegram username')),
                ('telegram_id', models.BigIntegerField(default=1, unique=True, verbose_name='Telegram ID')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Имя субкатегория')),
                ('title_uz', models.CharField(max_length=150, verbose_name='Subkategoriya nomi')),
                ('title_cn', models.CharField(max_length=150, verbose_name='Имя китайский')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'db_table': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Имя продукт')),
                ('title_uz', models.CharField(max_length=150, verbose_name='Maxsulot nomi')),
                ('title_cn', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя китайский')),
                ('price', models.PositiveIntegerField(verbose_name='Narxi')),
                ('structure', models.TextField(blank=True, null=True, verbose_name='Tarkibi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory', verbose_name='Subkategoriya')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Soni')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Maxsulot')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users', verbose_name='Foydalanuvchi'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=10, verbose_name='Maxsulot soni')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Narxi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users', verbose_name='Foydalanuvchi')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
