# Generated by Django 4.2 on 2023-04-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_cn',
            field=models.CharField(default='', max_length=150, verbose_name='Имя китайский'),
            preserve_default=False,
        ),
    ]
