# Generated by Django 4.2 on 2023-04-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_title_cn'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
